### ISSUE TITLE
Browser cache

### ISSUE THREAD

**Issue by TheRealNestar** [aFarkas/remote-list#7]
Hi there.

I noticed that the remoteList dropdown suggestions store previously used strings, (I guess) from the the browser's cache. As a matter of fact, when you clear the cache, the contents are back to what was set by the "source: function(value, response){ response(myJSONobject); }"

I understand the usefulness of this function, but is there a way to disable this functionality? 
Javascript is not my strong suit, regarding languages, and I really wish to control the autosuggest's contents.

tnx in advance :)

**Comment by aFarkas** [comment]
Does `autocomplete="off"` work for you?

**Comment by TheRealNestar** [comment]
Yes, it did!

My god, it always the simplest things!!! 
And Imagine that I solved another similar issue 2 days ago, with exactly this parameter, but I didn't think of it today.

thank you :)
